GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/66e6d5c1b1b7d5170e319600

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Adrian Marin 2",
  "number": "123456789"
}

###
DELETE http://localhost:3001/api/persons/66e6d5c502581094b180be39
